///////////
///Users///
///////////

#######################################
GET http://localhost:3000/api/users

#######################################
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "test_user",
  "password": "1234"
}

#######################################
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "test_15",
  "password": "password1"
}

#######################################
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "test_user",
  "password": "1234"
}

#################################################

GET http://localhost:3000/api/users/me

#######################################
GET http://localhost:3000/api/users/7

#######################################
DELETE http://localhost:3000/api/users/logout

#######################################
GET http://localhost:3000/api/logged-in-secret


/////////////
///Friends///
/////////////

#######################################
POST http://localhost:3000/api/friends
Content-Type: application/json

{
  "friendId": 4,
}

#######################################
GET http://localhost:3000/api/friends/5

#######################################
DELETE http://localhost:3000/api/friends

#######################################
PATCH http://localhost:3000/api/users



